---

- name: Check if kubeconfig exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeconfig

# See https://github.com/containerd/containerd/issues/4581
- name: Remove containerd config.toml
  file:
    path: /etc/containerd/config.toml
    state: absent
  when: not kubeconfig.stat.exists

- name: Restart containerd service
  service:
    name: containerd
    state: restarted
  when: not kubeconfig.stat.exists

- name: Join the node to cluster
  command: hostvars['{{ k8s_master_hostname }}']['join_command']
  when: not vagrant_execution

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777
  when: vagrant_execution

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  when: vagrant_execution